version: "3.4"

services:
  pythonsamplevscodedjangotutorial:
    image: pythonsamplevscodedjangotutorial
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - DEV=true
    volumes:
      - ./app:/app
    command:
      [
        "sh",
        "-c",
        "pip install debugpy -t /var/tmp && python /var/tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000 --nothreading --noreload",
      ]
    ports:
      - 8000:8000
      - 5678:5678
    environment:
      - DB_HOST=database
      - DB_NAME=devdb
      - DB_USER=dbuser
      - DB_PASSWORD=changeme
    depends_on:
      - database
  database:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=changeme
volumes:
  dev-db-data:
